# NOT USED, could be developed further

name: docker-compose
description: Runs docker compose

inputs:
  working_dir:
    description: Working directory
    required: false
    default: .
  compose_file:
    description: Docker compose file (can contain multiple files separated by `:`)
    required: false
  action:
    description: Action to perform
    required: true
  flags:
    description: Flags to pass to docker compose
    required: false
    default: "-d"
  remote_user:
    description: SSH user
    required: false
  remote_host:
    description: SSH host ip/domain
    required: false
  remote_host_port:
    description: SSH port
    required: false
    default: "22"
  dotenv_file:
    description: path to the dot-env file
    required: false

runs:
  using: composite

  steps:
    - name: Compose
      shell: bash
      env:
        COMPOSE_FILE: ${{ inputs.compose_file }}
        DOCKER_HOST: ssh://${{ inputs.remote_user }}@${{ inputs.remote_host }}:${{ inputs.remote_host_port }}
        COMPOSE_ENV_FILES: ${{ inputs.dotenv_file }}
      working-directory: ${{ inputs.working_dir }}
      run: |
        docker compose ${{ inputs.action }} ${{ inputs.flags }}

# This is a nice usage of docker provided variables,
# the `-d` should be always present in our case
# additionally `--remove-orphans` fits to my use case
