name: Setup sops
description: Setup sops on the runner

runs:
  using: "composite"
  steps:
    - name: Install SOPS
      shell: bash
      run: |
        curl -LsS https://github.com/getsops/sops/releases/download/v3.9.4/sops_3.9.4_amd64.deb \
          -o /tmp/sops.deb
        sudo dpkg -i /tmp/sops.deb
        sops --version
